### ISSUE TITLE
[FEAT] 초기 설정 및 파일 추가

### ISSUE THREAD

**Issue by vvtkfkddl11** [Ajou-UniA/uniA-ios#2]
## 💡 Issue
초기 설정 및 파일 추가

## 📝  todo
- [ ] 스토리보드 삭제
- [ ] NetworkResult, GenericResponse 파일 추가
- [ ] Login, Home, Schedule, InfoPage, MyPage 뷰컨트롤러 파일 추가
- [ ] Extension 파일 추가 (Constant, UIViewController+Extension)
